language: python
python:
- '2.7'
install:
- pip --version
script: python --version
deploy:
  provider: heroku
  api_key:
    secure: YD9D6LCNYwr6F5uTKuMl5yZisokkJmCzLFh/84EZrVEtfkJMGX8KZu3bYKuO0b1lB4K57IqyJHk3gbIZt3PB/1mIbOdeiXJAMixTq9+bH2009UrHpkOFCRF3+f3FroZG1wf0rpjOdn0nnK6uDEIl8x3H8lKxICIdozH88xaiGR4=
  app:
    master: yolped-1
  # provider intentially duplicated to deploy demo instance; see
  # https://github.com/travis-ci/travis-ci/issues/1272
  provider: heroku
  api_key:
    secure: YD9D6LCNYwr6F5uTKuMl5yZisokkJmCzLFh/84EZrVEtfkJMGX8KZu3bYKuO0b1lB4K57IqyJHk3gbIZt3PB/1mIbOdeiXJAMixTq9+bH2009UrHpkOFCRF3+f3FroZG1wf0rpjOdn0nnK6uDEIl8x3H8lKxICIdozH88xaiGR4=
  app:
    master: yolped-2
