language: python
python:
- '2.7'
install:
- pip --version
script: python --version
after_success:
  - chmod 600 .travis/deploybot_key.pem # this key should have push access
  - ssh-add .travis/deploybot_key.pem
