language: python
python:
- '2.7'
install:
- pip --version
script: python --version
after_success:
#  - chmod 600 .travis/deploybot_key.pem # this key should have push access
  - ssh-add .travis/deploybot_key.pem
  - echo 'OH HEY, let us fail!'
  - test 1 == 2
  - echo 'OH NO, why are we here?'
#  - git remote add deploy DEPLOY_REPO_URI_GOES_HERE
#  - git push deploy
